name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.1.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract new version
        id: version
        run: |
          cd dist/terraform-provider-authentik_linux_amd64/
          VERSION=$(./$(ls) -version)
          echo "##[set-output name=version]$VERSION"
      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: beryjuorg
          SENTRY_PROJECT: authentik-terraform-provider
          SENTRY_URL: https://sentry.beryju.org
        with:
          version: authentik-terraform-provider@${{ steps.version.outputs.version }}
