name: test-acc-authentik-master
on:
  push:
  schedule:
    - cron: '0 13 * * *'
jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: |
        make gen-api
        go mod download

    - name: Build
      run: |
        go build -v .
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '0.15.5'
          - '1.0.4'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: |
        make gen-api
        go mod download

    - name: TF acceptance tests
      timeout-minutes: 30
      env:
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
        AUTHENTIK_TOKEN: ${{ secrets.AUTHENTIK_TOKEN }}
        AUTHENTIK_URL: ${{ secrets.AUTHENTIK_URL }}
      run: |
        go test -timeout 0 -v -race -coverprofile=coverage.out -covermode=atomic -cover ./internal/provider/

    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
