name: test-acc-authentik-stable
on:
  pull_request:
  push:
  schedule:
    - cron: '0 13 * * *'
jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: |
        make gen-api
        go mod download

    - name: Build
      run: |
        go build -v .
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '0.15.5'
          - '1.0.4'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16'
      id: go

    - name: Setup authentik
      run: |
        sudo apt-get install -y pwgen
        # Because of a PostgreSQL limitation, only passwords up to 99 chars are supported
        # See https://www.postgresql.org/message-id/09512C4F-8CB9-4021-B455-EF4C4F0D55A0@amazon.com
        echo "PG_PASS=$(pwgen 40 1)" >> .env
        echo "AUTHENTIK_SECRET_KEY=$(pwgen 50 1)" >> .env
        # Skip if you don't want to enable error reporting
        echo "AUTHENTIK_ERROR_REPORTING__ENABLED=true" >> .env
        echo "AK_ADMIN_TOKEN=acc-test-token-key" >> .env
        # TODO: Remove when 2021.8 is released
        echo "AUTHENTIK_IMAGE=beryju.org/authentik/server" >> .env
        echo "AUTHENTIK_TAG=gh-next" >> .env
        echo "AUTHENTIK_OUTPOSTS__DOCKER_IMAGE_BASE=beryju.org/authentik/outpost-%(type)s:gh-next" >> .env
        wget https://raw.githubusercontent.com/goauthentik/authentik/version-2021.8/docker-compose.yml
        docker-compose pull -q
        docker-compose up -d
        timeout 600 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9000/api/v2beta/root/config/)" != "200" ]]; do sleep 5; done' || false

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Get dependencies
      run: |
        make gen-api
        go mod download

    - name: TF acceptance tests
      timeout-minutes: 30
      env:
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
        AUTHENTIK_TOKEN: "acc-test-token-key"
        AUTHENTIK_URL: http://localhost:9000
      run: |
        go test -timeout 0 -v -race -coverprofile=coverage.out -covermode=atomic -cover ./internal/provider/

    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
