name: update-schema

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check for updates
        id: update
        run: |
          wget https://raw.githubusercontent.com/goauthentik/authentik/master/schema.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-schema
          commit-message: Update Schema version
          title: Update Schema version
